apiVersion: v1
kind: Service
metadata:
  name: career-concierge
  namespace: career-concierge
spec:
  selector:
    app: career-concierge
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
